---
- hosts: all
  become: yes

  vars:
    hostname: "localhost"
    domain: "{{ hostname }}"
    selector: "default"
    admin_email: ""
    smtpd_tls_cert_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    smtpd_tls_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"

  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - name: Set the hostname
      hostname:
        name: "{{ hostname }}"

    - name: Get software for apt repository management
      apt:
        state: present
        name:
          - python3-apt
          - python3-pycurl

    - name: Install required packages
      apt:
        name:
          - postfix
          - dovecot-imapd
          - dovecot-lmtpd
          - dovecot-sieve
          - opendkim
          - opendkim-tools
          - postfix-policyd-spf-python
        state: present

    - name: Check to see if the DH parameters file exists
      stat: "path=/etc/postfix/dh2048.pem"
      register: dh_params_file

    - name: Generate the DH parameters file
      command: "openssl dhparam -out /etc/postfix/dh2048.pem 2048"
      when: not dh_params_file.stat.exists

    - name: Set Postfix default configuration
      lineinfile:
        dest: "/etc/postfix/main.cf"
        regexp: "{{ item.regexp }}"
        line: "{{ item.value }}"
        state: present
      with_items:
        - regexp: "^myhostname"
          value: "myhostname = {{ hostname }}"
        - regexp: "^mydestination"
          value: "mydestination = {{ domain }}"
        - regexp: "^disable_vrfy_command"
          value: "disable_vrfy_command = yes"
        - regexp: "^smtpd_tls_cert_file"
          value: "smtpd_tls_cert_file = {{ smtpd_tls_cert_file }}"
        - regexp: "^smtpd_tls_key_file"
          value: "smtpd_tls_key_file = {{ smtpd_tls_key_file }}"
        - regexp: "^smtpd_milters"
          value: "smtpd_milters = inet:localhost:8891"
        - regexp: "^milter_default_action"
          value: "milter_default_action = accept"
        - regexp: "^smtpd_tls_auth_only"
          value: "smtpd_tls_auth_only = yes"
        - regexp: "^smtpd_tls_mandatory_protocols"
          value: "smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1"
        - regexp: "^smtpd_tls_protocols"
          value: "smtpd_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1"
        - regexp: "^smtpd_tls_mandatory_ciphers"
          value: "smtpd_tls_mandatory_ciphers = medium"
        - regexp: "^tls_preempt_cipherlist"
          value: "tls_preempt_cipherlist = no"
        - regexp: "^smtpd_tls_dh1024_param_file"
          value: "smtpd_tls_dh1024_param_file = /etc/postfix/dh2048.pem"
        - regexp: "^tls_medium_cipherlist"
          value: "tls_medium_cipherlist = ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
        - regexp: "^policy-spf_time_limit"
          value: "policy-spf_time_limit = 3600"
        - regexp: "^smtpd_recipient_restrictions"
          value: "smtpd_recipient_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination, check_policy_service unix:private/policy-spf"
        - regexp: "^mailbox_transport"
          value: "mailbox_transport = lmtp:unix:private/dovecot-lmtp"
      notify: restart postfix

    - name: Enable Postfix smtp-auth
      copy:
        src: "files/dovecot/99-local-auth.conf"
        dest: "/etc/dovecot/conf.d/99-local-auth.conf"
        owner: root
        group: root
        mode: 0644
      notify: restart dovecot

    - name: Enable Dovecot LMTP
      copy:
        src: "files/dovecot/99-local-lmtp.conf"
        dest: "/etc/dovecot/conf.d/99-local-lmtp.conf"
        owner: root
        group: root
        mode: 0644
      notify: restart dovecot

    - name: Configure certificate settings for dovecot
      copy:
        content: |
          ssl_cert = <{{ smtpd_tls_cert_file }}
          ssl_key = <{{  smtpd_tls_key_file }}
        dest: /etc/dovecot/conf.d/99-local-ssl.conf
      notify: restart dovecot

    - name: Setup submission and smtps port
      blockinfile:
        state: present
        insertafter: EOF
        dest: /etc/postfix/master.cf
        content: |
          smtps inet n       -       y       -       -       smtpd
             -o syslog_name=postfix/smtps
             -o smtpd_tls_wrappermode=yes
             -o smtpd_sasl_auth_enable=yes
             -o smtpd_sasl_type=dovecot
             -o smtpd_sasl_path=private/auth
             -o smtpd_sasl_security_options=noanonymous
             -o smtpd_reject_unlisted_recipient=no
             -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
          submission inet n       -       y       -       -       smtpd
             -o syslog_name=postfix/submission
             -o smtpd_tls_security_level=encrypt
             -o smtpd_sasl_auth_enable=yes
             -o smtpd_sasl_type=dovecot
             -o smtpd_sasl_path=private/auth
             -o smtpd_sasl_security_options=noanonymous
             -o smtpd_tls_auth_only=yes
             -o smtpd_reject_unlisted_recipient=no
             -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
          policy-spf unix  -       n       n       -       -       spawn
              user=nobody argv=/usr/bin/policyd-spf
      notify: restart postfix

    - name: Create the directory (if it doesn't exist) for the DKIM signing keys
      file:
        state: directory
        path: /etc/dkimkeys
        owner: opendkim
        group: opendkim
        mode: '0700'

    - name: Check to see if the signing key already exists
      stat: "path=/etc/dkimkeys/{{ selector }}.private"
      register: signing_key_file

    - name: Generate the signing keys
      command: "opendkim-genkey -D /etc/dkimkeys -b 2048 -s {{ selector }}"
      when: not signing_key_file.stat.exists

    - name: Change key permissions
      file:
        path: "/etc/dkimkeys/{{ selector }}.private"
        owner: opendkim
        group: opendkim

    - name: Modify DKIM configuration
      blockinfile:
        insertafter: EOF
        dest: /etc/opendkim.conf
        content: |
          Mode                   sv
          Domain                 {{ domain }}
          Selector               {{ selector }}
          KeyFile                /etc/dkimkeys/{{ selector }}.private
      notify: restart opendkim

    - name: Change DKIM socket setting
      lineinfile:
        dest: /etc/opendkim.conf
        regexp: "^Socket"
        line: "Socket                  inet:8891@localhost"
        state: present
      notify: restart opendkim

  handlers:
    - name: restart postfix
      service: name=postfix state=restarted

    - name: restart dovecot
      service: name=dovecot state=restarted

    - name: restart opendkim
      service: name=opendkim state=restarted